export const addresses = [
	{
		id: 512,
		descripcion: "Ventilador",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 513,
		descripcion: "Atomizador",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 514,
		descripcion: "Valvula Rot.",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 515,
		descripcion: "Quemador",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 516,
		descripcion: "Bomba",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 517,
		descripcion: "Martillos",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 520,
		descripcion: "Lavador",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 568,
		descripcion: "Temp de entrada (SETPOINT)",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "ºC",
		precision: 0,
		realTime: true,
		grupo: 1,
	},
	{
		id: 569,
		descripcion: "Temp de entrada",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "ºC",
		precision: 0,
		realTime: true,
		grupo: 1,
	},
	{
		id: 573,
		descripcion: "Frecuencia de Red",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "Hz",
		precision: 2,
		realTime: true,
		grupo: 99,
	},
	{
		id: 574,
		descripcion: "Tension L1 + L2",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "v",
		precision: 1,
		realTime: true,
		grupo: 99,
	},
	{
		id: 575,
		descripcion: "Tension L2 + L3",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "v",
		precision: 1,
		realTime: true,
		grupo: 99,
	},
	{
		id: 576,
		descripcion: "Tension L1 + L3",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "v",
		precision: 1,
		realTime: true,
		grupo: 99,
	},
	{
		id: 577,
		descripcion: "Consumo de Ventilador",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "A",
		precision: 2,
		realTime: true,
		grupo: 99,
	},
	{
		id: 579,
		descripcion: "Temp de salida (SP)",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "ºC",
		precision: 0,
		realTime: true,
		grupo: 2,
	},
	{
		id: 580,
		descripcion: "Temp de Salida",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "ºC",
		precision: 0,
		realTime: true,
		grupo: 2,
	},
	{
		id: 581,
		descripcion: "Bomba de Alimentacion",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "%",
		precision: 1,
		realTime: true,
		grupo: 3,
	},
	{
		id: 582,
		descripcion: "Potencia de Quemador",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "%",
		precision: 1,
		realTime: true,
		grupo: 3,
	},
	{
		id: 584,
		descripcion: "Cons. de Bomba de Alim.",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "A",
		precision: 2,
		realTime: true,
		grupo: 99,
	},
	{
		id: 586,
		descripcion: "Consumo de Atomizador",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "A",
		precision: 2,
		realTime: true,
		grupo: 99,
	},
	{
		id: 592,
		descripcion: "Tension L1 + N",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "v",
		precision: 1,
		realTime: true,
		grupo: 4,
	},
	{
		id: 594,
		descripcion: "Tension L2 + N",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "v",
		precision: 1,
		realTime: true,
		grupo: 4,
	},
	{
		id: 596,
		descripcion: "Tension L3 + N",
		value: "",
		listable: true,
		esEvento: false,
		unidad: "v",
		precision: 1,
		realTime: true,
		grupo: 4,
	},
	{
		id: 1514,
		descripcion: "Temp de Apagado Automático",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "ºC",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 1515,
		descripcion: "Int. golpes del martillo",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "seg",
		precision: 0,
		realTime: true,
		grupo: 99,
	},
	{
		id: 1518,
		descripcion: "Velocidad Ventilador (SP)",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "",
		precision: 2,
		realTime: true,
		grupo: 99,
	},
	{
		id: 1523,
		descripcion: "Velocidad Atomizador (SP)",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "",
		precision: 2,
		realTime: true,
		grupo: 99,
	},
	{
		id: 1717,
		descripcion: "Cod de Prod",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 1712,
		descripcion: "Nro Pda de Prod(1)",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 1727,
		descripcion: "Nro Pda de Prod(2)",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 1722,
		descripcion: "Barra del Prod",
		value: "",
		listable: false,
		esEvento: false,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3113,
		descripcion: "Apag.Autom.",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3183,
		descripcion: "Login Encargado 1",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3186,
		descripcion: "Login Encargado 2",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3189,
		descripcion: "Login Encargado 3",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3192,
		descripcion: "Login Encargado 4",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3195,
		descripcion: "Login Encargado 5",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3198,
		descripcion: "Login Encargado 6",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3201,
		descripcion: "Login Mantenimiento 1",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3204,
		descripcion: "Login Mantenimiento 2",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3207,
		descripcion: "Login Mantenimiento 3",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
	{
		id: 3210,
		descripcion: "Login RyR",
		value: "",
		listable: false,
		esEvento: true,
		unidad: "",
		precision: 0,
		realTime: false,
		grupo: 99,
	},
];
